export interface Theme {
  id: string;
  name: string;
  description: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
  };
  vibe: 'dark' | 'colorful' | 'professional' | 'retro' | 'nature' | 'luxury' | 'minimal' | 'urban' | 'tech' | 'sport' | 'editorial';
}

export const THEMES: Theme[] = [
  {
    id: 'spiderman',
    name: 'Spiderman',
    description: 'Vibrante y heroico, con contrastes urbanos y dinamismo arácnido',
    colors: { primary: '#1A1A1A', secondary: '#F5F5F5', accent: '#E9272A', background: '#F5F5F5' },
    vibe: 'colorful',
  },
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    description: 'Elegancia histórica, pureza blanca y toques de realeza deportiva',
    colors: { primary: '#00529F', secondary: '#FFFFFF', accent: '#FEBE10', background: '#FAFAFA' },
    vibe: 'sport',
  },
  {
    id: 'barbie',
    name: 'Barbie',
    description: 'Rosa icónico, glamuroso y lleno de energía optimista',
    colors: { primary: '#E8218C', secondary: '#FFFFFF', accent: '#FF69B4', background: '#FFF0F7' },
    vibe: 'colorful',
  },
  {
    id: 'f1',
    name: 'Fórmula 1',
    description: 'Velocidad, precisión técnica y un acabado de alto rendimiento',
    colors: { primary: '#1E1E1E', secondary: '#FFFFFF', accent: '#E10600', background: '#F5F5F5' },
    vibe: 'sport',
  },
  {
    id: 'nasa',
    name: 'NASA',
    description: 'Exploración espacial, técnico, limpio y con visión de futuro',
    colors: { primary: '#0B3D91', secondary: '#FFFFFF', accent: '#FC3D21', background: '#F0F6FF' },
    vibe: 'tech',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Futurismo distópico, luces de neón y contrastes de alta tecnología',
    colors: { primary: '#0D0221', secondary: '#FFFFFF', accent: '#FF00E5', background: '#0D0221' },
    vibe: 'dark',
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Brillo nocturno, energía eléctrica sobre un fondo profundo',
    colors: { primary: '#0D0D0D', secondary: '#FFFFFF', accent: '#FF0080', background: '#0D0D0D' },
    vibe: 'dark',
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Minimalismo sofisticado en modo oscuro para ojos modernos',
    colors: { primary: '#121212', secondary: '#E0E0E0', accent: '#BB86FC', background: '#0D0D0D' },
    vibe: 'dark',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Espacios limpios, tipografía clara y enfoque absoluto en el contenido',
    colors: { primary: '#FFFFFF', secondary: '#333333', accent: '#888888', background: '#FAFAFA' },
    vibe: 'minimal',
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Orgánico, fresco y terrenal; ideal para perfiles sostenibles',
    colors: { primary: '#2D5016', secondary: '#FFFFFF', accent: '#8BC34A', background: '#F5F5DC' },
    vibe: 'nature',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    description: 'Nostalgia de los 80, estética glitch y atardeceres digitales surrealistas',
    colors: { primary: '#1A1A2E', secondary: '#FFFFFF', accent: '#FF71CE', background: '#16213E' },
    vibe: 'retro',
  },
  {
    id: 'steampunk',
    name: 'Steampunk',
    description: 'Revolución industrial, engranajes de cobre y elegancia victoriana mecánica',
    colors: { primary: '#4B3621', secondary: '#C5B358', accent: '#8B4513', background: '#F5E6D0' },
    vibe: 'retro',
  },
  {
    id: 'matrix',
    name: 'Matrix',
    description: 'Lluvia digital, terminal de comandos y una estética de código puro',
    colors: { primary: '#0D0208', secondary: '#00FF41', accent: '#003B00', background: '#0D0208' },
    vibe: 'dark',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    description: 'Lujo clásico de los años 20, patrones geométricos y dorado premium',
    colors: { primary: '#1B1B1B', secondary: '#E5E4E2', accent: '#D4AF37', background: '#F5F4F0' },
    vibe: 'luxury',
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    description: 'Funcionalidad geométrica, colores primarios y equilibrio artístico',
    colors: { primary: '#1B1B1B', secondary: '#FFFFFF', accent: '#E63946', background: '#F1FAEE' },
    vibe: 'professional',
  },
  {
    id: 'nordic',
    name: 'Nordic',
    description: 'Minimalismo escandinavo, tonos fríos y calidez funcional',
    colors: { primary: '#2F3E46', secondary: '#CAD2C5', accent: '#84A98C', background: '#F5F5F5' },
    vibe: 'minimal',
  },
  {
    id: 'coffee-shop',
    name: 'Coffee Shop',
    description: 'Acogedor, texturas de grano de café y un ambiente de trabajo relajado',
    colors: { primary: '#6F4E37', secondary: '#FED8B1', accent: '#A67B5B', background: '#FDF6EE' },
    vibe: 'nature',
  },
  {
    id: 'star-wars-sith',
    name: 'Sith Lord',
    description: 'Poder absoluto, oscuridad profunda y toques de rojo láser',
    colors: { primary: '#000000', secondary: '#E6E6E6', accent: '#990000', background: '#0A0000' },
    vibe: 'dark',
  },
  {
    id: 'star-wars-jedi',
    name: 'Jedi Order',
    description: 'Serenidad, túnicas de lino y la luz de un sable azul',
    colors: { primary: '#F5F5DC', secondary: '#4682B4', accent: '#2E8B57', background: '#F5F5DC' },
    vibe: 'colorful',
  },
  {
    id: 'forest-zen',
    name: 'Zen Garden',
    description: 'Paz visual, equilibrio natural y frescura botánica',
    colors: { primary: '#718355', secondary: '#E9F5DB', accent: '#97A97C', background: '#F0F5E8' },
    vibe: 'nature',
  },
  {
    id: 'vintage-polaroid',
    name: 'Vintage Polaroid',
    description: 'Fotografía retro, colores lavados por el sol y bordes nostálgicos',
    colors: { primary: '#A04000', secondary: '#FEF9E7', accent: '#FAD7A0', background: '#FEF9E7' },
    vibe: 'retro',
  },
  {
    id: 'deep-sea',
    name: 'Deep Sea',
    description: 'Profundidad oceánica, misterio marino y fluidez profesional',
    colors: { primary: '#001219', secondary: '#94D2BD', accent: '#0A9396', background: '#F0F7F9' },
    vibe: 'nature',
  },
  {
    id: 'volcano',
    name: 'Volcanic',
    description: 'Intenso, dramático y con el calor del magma líquido',
    colors: { primary: '#370617', secondary: '#FFFFFF', accent: '#FFBA08', background: '#1A0A08' },
    vibe: 'colorful',
  },
  {
    id: 'sunset-beach',
    name: 'Sunset Beach',
    description: 'Calidez veraniega, degradados de cielo y frescura costera',
    colors: { primary: '#FF9E00', secondary: '#FFFFFF', accent: '#FF5400', background: '#FFF8F0' },
    vibe: 'colorful',
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Diseño de ingeniería, planos técnicos y precisión arquitectónica',
    colors: { primary: '#0047AB', secondary: '#FFFFFF', accent: '#3366CC', background: '#F0F6FB' },
    vibe: 'professional',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Consola retro, baja fatiga visual y estética de desarrollador senior',
    colors: { primary: '#002B36', secondary: '#93A1A1', accent: '#859900', background: '#002B36' },
    vibe: 'dark',
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    description: 'Prestigio, éxito y un acabado metálico de alta gama',
    colors: { primary: '#996515', secondary: '#CFB53B', accent: '#AF9630', background: '#1A1510' },
    vibe: 'luxury',
  },
  {
    id: 'sakura',
    name: 'Sakura Night',
    description: 'Cerezos japoneses bajo la luna, colores florales y nocturnos',
    colors: { primary: '#581845', secondary: '#FF5733', accent: '#900C3F', background: '#1A0A15' },
    vibe: 'dark',
  },
  {
    id: 'minecraft',
    name: 'Pixel Craft',
    description: 'Estética de bloques, creatividad modular y nostalgia de 8 bits',
    colors: { primary: '#3C2415', secondary: '#629232', accent: '#7C7C7C', background: '#E8E8E8' },
    vibe: 'retro',
  },
  {
    id: 'galaxy',
    name: 'Nebula',
    description: 'Polvo estelar, púrpuras cósmicos y profundidad infinita',
    colors: { primary: '#240046', secondary: '#FFFFFF', accent: '#9D4EDD', background: '#180033' },
    vibe: 'dark',
  },
  {
    id: 'retro-gaming',
    name: 'Arcade',
    description: 'Colores primarios brillantes, estilo joystick y energía de los 90',
    colors: { primary: '#0000FF', secondary: '#FF0000', accent: '#FFD700', background: '#1A1A1A' },
    vibe: 'retro',
  },
  {
    id: 'monochrome-steel',
    name: 'Steel',
    description: 'Industrial, sólido y con un brillo metálico profesional',
    colors: { primary: '#212529', secondary: '#CED4DA', accent: '#6C757D', background: '#F5F5F5' },
    vibe: 'professional',
  },
  {
    id: 'desert',
    name: 'Sahara',
    description: 'Dunas infinitas, calidez árida y luz solar intensa',
    colors: { primary: '#E2711D', secondary: '#FEE440', accent: '#FFB627', background: '#FFF8F0' },
    vibe: 'colorful',
  },
  {
    id: 'glitch-art',
    name: 'Glitch',
    description: 'Distorsión digital controlada, vanguardia y error estético',
    colors: { primary: '#000000', secondary: '#FFFFFF', accent: '#FF00FF', background: '#000000' },
    vibe: 'dark',
  },
  {
    id: 'matcha',
    name: 'Matcha Tea',
    description: 'Orgánico suave, tranquilidad herbal y estética limpia',
    colors: { primary: '#ADC178', secondary: '#F0EAD2', accent: '#A98467', background: '#F8F6F0' },
    vibe: 'nature',
  },
  {
    id: 'dracula',
    name: 'Dracula Theme',
    description: 'Inspirado en el famoso tema de código, oscuro pero colorido',
    colors: { primary: '#282A36', secondary: '#F8F8F2', accent: '#FF79C6', background: '#1E1F29' },
    vibe: 'dark',
  },
  {
    id: 'iceberg',
    name: 'Arctic',
    description: 'Frío glacial, profesionalismo sólido y claridad de cristal',
    colors: { primary: '#293241', secondary: '#FFFFFF', accent: '#98C1D9', background: '#F0F8FF' },
    vibe: 'minimal',
  },
  {
    id: 'pop-art',
    name: 'Warhol Pop',
    description: 'Alto contraste, colores saturados y expresión artística audaz',
    colors: { primary: '#E64A19', secondary: '#FFFFFF', accent: '#F3C677', background: '#FFF8E1' },
    vibe: 'colorful',
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard',
    description: 'Estética educativa, tiza sobre pizarra y creatividad académica',
    colors: { primary: '#2D2D2D', secondary: '#FFFFFF', accent: '#6B8E23', background: '#2D2D2D' },
    vibe: 'retro',
  },
  {
    id: 'leather-bound',
    name: 'Library',
    description: 'Libros antiguos, cuero refinado y sabiduría clásica',
    colors: { primary: '#3D2B1F', secondary: '#FEFAE0', accent: '#D4A373', background: '#F5F0E8' },
    vibe: 'luxury',
  },
  {
    id: 'marathon',
    name: 'Runner',
    description: 'Energía atlética, frescura de entrenamiento y movimiento',
    colors: { primary: '#00FF7F', secondary: '#F5FFFA', accent: '#008080', background: '#F0FFF5' },
    vibe: 'sport',
  },
  {
    id: 'wine-cellar',
    name: 'Bordeaux',
    description: 'Madurez, cuerpo rico y un tono burdeos profesional',
    colors: { primary: '#4A0E0E', secondary: '#FFFFFF', accent: '#800000', background: '#F5F0F0' },
    vibe: 'luxury',
  },
  {
    id: 'bloomberg',
    name: 'Terminal Pro',
    description: 'Finanzas globales, datos en tiempo real y autoridad económica',
    colors: { primary: '#1A1A1A', secondary: '#FFFFFF', accent: '#FF9900', background: '#0D0D0D' },
    vibe: 'dark',
  },
  {
    id: 'origami',
    name: 'Paper Fold',
    description: 'Geometría de papel, sombras suaves y minimalismo táctil',
    colors: { primary: '#FDFCF0', secondary: '#C9ADA7', accent: '#9A8C98', background: '#FDFCF0' },
    vibe: 'minimal',
  },
  {
    id: 'high-fashion',
    name: 'Vogue',
    description: 'Pasarela, tipografía editorial y contraste de alto nivel',
    colors: { primary: '#000000', secondary: '#FFFFFF', accent: '#D4AF37', background: '#FAFAFA' },
    vibe: 'luxury',
  },
  {
    id: 'tech-startup',
    name: 'Unicorn',
    description: 'Ilustraciones modernas, tonos pastel vibrantes y espíritu ágil',
    colors: { primary: '#3F3D56', secondary: '#F2F2F2', accent: '#6C63FF', background: '#FAFAFA' },
    vibe: 'colorful',
  },
  {
    id: 'mountain-climb',
    name: 'Everest',
    description: 'Superación, aire puro de montaña y tonos rocosos',
    colors: { primary: '#1B263B', secondary: '#E0E1DD', accent: '#415A77', background: '#F5F5F5' },
    vibe: 'nature',
  },
  {
    id: 'solar-punk',
    name: 'Solarpunk',
    description: 'Futuro verde, tecnología armoniosa con la naturaleza',
    colors: { primary: '#22577A', secondary: '#C7F9CC', accent: '#57CC99', background: '#F0FFF5' },
    vibe: 'nature',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    description: 'Coches deportivos de los 80, cuadrículas y atardeceres magenta',
    colors: { primary: '#2B2139', secondary: '#FFFFFF', accent: '#FF0055', background: '#1A1025' },
    vibe: 'retro',
  },
  {
    id: 'mediterranean',
    name: 'Santorini',
    description: 'Azul cobalto, paredes blancas y sol radiante',
    colors: { primary: '#005DAA', secondary: '#FFD700', accent: '#FFFFFF', background: '#F5F8FF' },
    vibe: 'colorful',
  },
  {
    id: 'luxury-watch',
    name: 'Chronograph',
    description: 'Maquinaria suiza, precisión de acero y bronce',
    colors: { primary: '#1C1C1C', secondary: '#C0C0C0', accent: '#B87333', background: '#F5F5F5' },
    vibe: 'luxury',
  },
  {
    id: 'autumn-leaf',
    name: 'Autumn',
    description: 'Hojas secas, calidez hogareña y cambio de estación',
    colors: { primary: '#603808', secondary: '#FB8B24', accent: '#9A031E', background: '#FFF8F0' },
    vibe: 'nature',
  },
  {
    id: 'claymorphism',
    name: 'Clay',
    description: 'Efectos 3D suaves, aspecto de arcilla amable y moderno',
    colors: { primary: '#B8C1EC', secondary: '#EEBBE7', accent: '#F0F2F5', background: '#F0F2F5' },
    vibe: 'minimal',
  },
  {
    id: 'brutalism',
    name: 'Brutalist',
    description: 'Crudo, sin pulir, tipografías masivas y diseño directo',
    colors: { primary: '#000000', secondary: '#FFFFFF', accent: '#FF3E00', background: '#F5F5F5' },
    vibe: 'professional',
  },
  {
    id: 'sketchbook',
    name: 'Draft',
    description: 'Dibujado a mano, carboncillo y textura de papel de dibujo',
    colors: { primary: '#5D4037', secondary: '#212121', accent: '#9E9E9E', background: '#FFF9EB' },
    vibe: 'retro',
  },
  {
    id: 'tokyo-street',
    name: 'Shibuya',
    description: 'Noche urbana, luces rojas y asfalto mojado',
    colors: { primary: '#1A1A1D', secondary: '#FFFFFF', accent: '#950740', background: '#0D0D10' },
    vibe: 'urban',
  },
  {
    id: 'botanical',
    name: 'Greenhouse',
    description: 'Exuberancia vegetal, frescura y crecimiento orgánico',
    colors: { primary: '#1B4332', secondary: '#D8F3DC', accent: '#2D6A4F', background: '#F0FFF5' },
    vibe: 'nature',
  },
  {
    id: 'diamond',
    name: 'Jewel',
    description: 'Brillo cristalino, facetas de diamante y claridad pura',
    colors: { primary: '#0077B6', secondary: '#FFFFFF', accent: '#00D4FF', background: '#F0F8FF' },
    vibe: 'luxury',
  },
  {
    id: 'poker-night',
    name: 'Casino Royale',
    description: 'Fieltro verde, apuestas altas y elegancia de esmoquin',
    colors: { primary: '#0B6623', secondary: '#FFFFFF', accent: '#D4AF37', background: '#1A3D1A' },
    vibe: 'luxury',
  },
  {
    id: 'space-x',
    name: 'Interstellar',
    description: 'Exploración comercial, minimalismo aeroespacial y cohetes',
    colors: { primary: '#000000', secondary: '#FFFFFF', accent: '#005288', background: '#0A0A0A' },
    vibe: 'tech',
  },
  {
    id: 'tennis-court',
    name: 'Grand Slam',
    description: 'Pelota de tenis, polvo de ladrillo y frescura deportiva',
    colors: { primary: '#BC6C25', secondary: '#FFFFFF', accent: '#E9FF70', background: '#FFF8F5' },
    vibe: 'sport',
  },
  {
    id: 'vinyl-record',
    name: 'Analog Music',
    description: 'Surcos de vinilo, calidez analógica y diseño de carátula',
    colors: { primary: '#121212', secondary: '#FFD700', accent: '#E5E5E5', background: '#1A1A1A' },
    vibe: 'retro',
  },
  {
    id: 'renaissance',
    name: 'Da Vinci',
    description: 'Papel pergamino, estudios anatómicos y arte clásico',
    colors: { primary: '#4E342E', secondary: '#BDBDBD', accent: '#A1887F', background: '#F5F0E8' },
    vibe: 'luxury',
  },
  {
    id: 'subway-map',
    name: 'Metro',
    description: 'Líneas de conexión, claridad de tránsito y orden urbano',
    colors: { primary: '#0039A6', secondary: '#FFFFFF', accent: '#EE352E', background: '#FAFAFA' },
    vibe: 'urban',
  },
  {
    id: 'avocado-toast',
    name: 'Brunch',
    description: 'Estética foodie, tonos verdes suaves y luz de mañana',
    colors: { primary: '#556B2F', secondary: '#FFFDD0', accent: '#BDB76B', background: '#FFFFF5' },
    vibe: 'nature',
  },
  {
    id: 'matrix-reloaded',
    name: 'Source Code',
    description: 'Más datos, más profundidad y el verde icónico del código',
    colors: { primary: '#0D0208', secondary: '#008F11', accent: '#00FF41', background: '#0D0208' },
    vibe: 'dark',
  },
  {
    id: 'cotton-candy',
    name: 'Pastel Dream',
    description: 'Suavidad infantil, nubes de azúcar y colores de ensueño',
    colors: { primary: '#FFC8DD', secondary: '#CDB4DB', accent: '#BDE0FE', background: '#FFF8FF' },
    vibe: 'colorful',
  },
  {
    id: 'lava-lamp',
    name: 'Groovy',
    description: 'Psicodelia suave, formas fluidas y colores de los 70',
    colors: { primary: '#E91E63', secondary: '#3F51B5', accent: '#9C27B0', background: '#1A1A2E' },
    vibe: 'retro',
  },
  {
    id: 'underground-club',
    name: 'Techno',
    description: 'Oscuridad industrial, bajos profundos y luz de láser cian',
    colors: { primary: '#000000', secondary: '#00ADB5', accent: '#393E46', background: '#0A0A0A' },
    vibe: 'dark',
  },
  {
    id: 'safari',
    name: 'Serengeti',
    description: 'Tonos tierra, aventura salvaje y sol de sabana',
    colors: { primary: '#BC6C25', secondary: '#FEFAE0', accent: '#283618', background: '#FFF8F0' },
    vibe: 'nature',
  },
  {
    id: 'blueprint-v2',
    name: 'Architect',
    description: 'Líneas de construcción, estructura sólida y diseño técnico',
    colors: { primary: '#1B263B', secondary: '#E0E1DD', accent: '#415A77', background: '#F5F8FF' },
    vibe: 'professional',
  },
  {
    id: 'chess-master',
    name: 'Grandmaster',
    description: 'Estrategia pura, casillas de madera y contraste intelectual',
    colors: { primary: '#313131', secondary: '#FFFFFF', accent: '#8B4513', background: '#F5F5F5' },
    vibe: 'professional',
  },
  {
    id: 'comic-book',
    name: 'Marvelous',
    description: 'Onomatopeyas, sombreado de puntos Ben-Day y acción',
    colors: { primary: '#000000', secondary: '#FFFFFF', accent: '#F0131E', background: '#FAFAFA' },
    vibe: 'colorful',
  },
  {
    id: 'neon-jungle',
    name: 'Electric Forest',
    description: 'Naturaleza radioactiva, verdes brillantes y energía vital',
    colors: { primary: '#004B23', secondary: '#CCFF33', accent: '#38B000', background: '#0A1A0A' },
    vibe: 'dark',
  },
  {
    id: 'cyber-security',
    name: 'Firewall',
    description: 'Protección, datos encriptados y seguridad tecnológica',
    colors: { primary: '#0B0D17', secondary: '#FFFFFF', accent: '#3B82F6', background: '#0D0F17' },
    vibe: 'tech',
  },
  {
    id: 'smoothie-bar',
    name: 'Tropical',
    description: 'Fruta fresca, vitaminas visuales y alegría veraniega',
    colors: { primary: '#1982C4', secondary: '#FF595E', accent: '#FFCA3A', background: '#FFF8F5' },
    vibe: 'colorful',
  },
  {
    id: 'film-noir',
    name: 'Detective',
    description: 'Sombras dramáticas, misterio y blanco y negro cinematográfico',
    colors: { primary: '#000000', secondary: '#FFFFFF', accent: '#616161', background: '#1A1A1A' },
    vibe: 'dark',
  },
  {
    id: 'minimal-gold',
    name: 'Executive',
    description: 'Minimalismo de lujo, toques dorados y aire corporativo de élite',
    colors: { primary: '#FFFFFF', secondary: '#D4AF37', accent: '#1A1A1A', background: '#FAFAFA' },
    vibe: 'luxury',
  },
  {
    id: 'deep-purple',
    name: 'Deep Purple',
    description: 'Creatividad nocturna, mística y elegancia púrpura',
    colors: { primary: '#240046', secondary: '#FFFFFF', accent: '#7B2CBF', background: '#180030' },
    vibe: 'dark',
  },
  {
    id: 'matcha-latte',
    name: 'Wellness',
    description: 'Equilibrio mental, calma visual y tonos saludables',
    colors: { primary: '#3A5A40', secondary: '#DAD7CD', accent: '#A3B18A', background: '#F8F6F0' },
    vibe: 'nature',
  },
  {
    id: 'racing-track',
    name: 'Circuit',
    description: 'Asfalto, líneas de meta y adrenalina mecánica',
    colors: { primary: '#111111', secondary: '#FFFFFF', accent: '#E10600', background: '#1A1A1A' },
    vibe: 'sport',
  },
  {
    id: 'luxury-car',
    name: 'Gran Turismo',
    description: 'Asientos de cuero, tablero de fibra de carbono y potencia',
    colors: { primary: '#000000', secondary: '#C0C0C0', accent: '#8B0000', background: '#0D0D0D' },
    vibe: 'luxury',
  },
  {
    id: 'ancient-greece',
    name: 'Olympus',
    description: 'Mármol blanco, azul mediterráneo y laureles de oro',
    colors: { primary: '#0047AB', secondary: '#FFFFFF', accent: '#FFD700', background: '#F5F5F5' },
    vibe: 'luxury',
  },
  {
    id: 'biohazard',
    name: 'Biohazard',
    description: 'Advertencia, energía química y contraste industrial',
    colors: { primary: '#1A1A1A', secondary: '#FFFF00', accent: '#32CD32', background: '#0D0D0D' },
    vibe: 'tech',
  },
  {
    id: 'blueprint-dark',
    name: 'Night Plan',
    description: 'Planos de ingeniería en modo nocturno, profesional y técnico',
    colors: { primary: '#001B44', secondary: '#C0C0C0', accent: '#3A6EA5', background: '#0A1525' },
    vibe: 'dark',
  },
  {
    id: 'pop-culture-80s',
    name: 'Eighties',
    description: 'Cintas de casete, colores neón saturados y cultura pop pura',
    colors: { primary: '#000000', secondary: '#FFFF00', accent: '#FF00FF', background: '#0A0A0A' },
    vibe: 'retro',
  },
  {
    id: 'modern-art',
    name: 'Museum',
    description: 'Espacio de galería, enfoque en la obra y aire sofisticado',
    colors: { primary: '#1A1A1A', secondary: '#FFFFFF', accent: '#E63946', background: '#FAFAFA' },
    vibe: 'luxury',
  },
  {
    id: 'zen-stones',
    name: 'Stones',
    description: 'Equilibrio, paciencia y texturas minerales suaves',
    colors: { primary: '#4A4A4A', secondary: '#FFFFFF', accent: '#D3D3D3', background: '#F5F5F5' },
    vibe: 'minimal',
  },
  {
    id: 'quantum-physics',
    name: 'Quantum',
    description: 'Partículas, energía atómica y misterio científico',
    colors: { primary: '#0F0C29', secondary: '#FFFFFF', accent: '#302B63', background: '#0A0820' },
    vibe: 'tech',
  },
  {
    id: 'startup-vibrant',
    name: 'Growth',
    description: 'Escalabilidad, energía emprendedora y colores dinámicos',
    colors: { primary: '#4361EE', secondary: '#F72585', accent: '#4CC9F0', background: '#FAFAFA' },
    vibe: 'colorful',
  },
  {
    id: 'industrial-loft',
    name: 'Brooklyn',
    description: 'Ladrillo visto, vigas de hierro y calidez urbana',
    colors: { primary: '#3E363F', secondary: '#F4EBD0', accent: '#B68D40', background: '#F5F0E8' },
    vibe: 'urban',
  },
  {
    id: 'luxury-diamond',
    name: 'Platinum',
    description: 'Metal precioso, exclusividad y brillo monocromático',
    colors: { primary: '#E5E4E2', secondary: '#8E8E8E', accent: '#B4B4B4', background: '#F5F5F5' },
    vibe: 'luxury',
  },
  {
    id: 'ocean-tide',
    name: 'Tide',
    description: 'Movimiento fluido, frescura marina y claridad azul',
    colors: { primary: '#0077B6', secondary: '#CAF0F8', accent: '#00B4D8', background: '#F0F8FF' },
    vibe: 'nature',
  },
  {
    id: 'mountain-hike',
    name: 'Alps',
    description: 'Cumbres nevadas, aire puro y toques de aventura roja',
    colors: { primary: '#2B2D42', secondary: '#EDF2F4', accent: '#EF233C', background: '#F5F5F5' },
    vibe: 'nature',
  },
  {
    id: 'space-nebula',
    name: 'Orion',
    description: 'Nubes de gas estelar, misterio cósmico y profundidad',
    colors: { primary: '#0B0D17', secondary: '#FFFFFF', accent: '#916BBF', background: '#050810' },
    vibe: 'dark',
  },
  {
    id: 'classic-typewriter',
    name: 'Hemingway',
    description: 'Escritura analógica, tinta negra y papel antiguo',
    colors: { primary: '#2F4F4F', secondary: '#F5F5DC', accent: '#8B4513', background: '#F5F0DC' },
    vibe: 'editorial',
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Profesional y confiable, ideal para perfiles empresariales',
    colors: { primary: '#1E3A5F', secondary: '#FFFFFF', accent: '#2563EB', background: '#F8FAFC' },
    vibe: 'professional',
  },
];

export const MAX_PORTFOLIOS_PER_USER = 5;

export type JobStatus =
  | 'PENDING_SCRAPE'
  | 'SCRAPING'
  | 'SCRAPED'
  | 'PENDING_BUILD'
  | 'BUILDING'
  | 'DEPLOYING'
  | 'DONE'
  | 'FAILED';

export interface Job {
  id: string;
  userUuid: string;
  linkedinUrl: string;
  theme: string;
  status: JobStatus;
  scrapedData: Record<string, unknown> | null;
  githubRepoUrl: string | null;
  deployedUrl: string | null;
  screenshotUrl: string | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
}

export const STATUS_CONFIG: Record<JobStatus, { label: string; color: string; bg: string; icon: string }> = {
  PENDING_SCRAPE: { label: 'Queued', color: '#6B7280', bg: '#F3F4F6', icon: 'Clock' },
  SCRAPING: { label: 'Fetching', color: '#2563EB', bg: '#EFF6FF', icon: 'Loader' },
  SCRAPED: { label: 'Retrieved', color: '#0891B2', bg: '#ECFEFF', icon: 'Check' },
  PENDING_BUILD: { label: 'Queued Build', color: '#7C3AED', bg: '#F5F3FF', icon: 'Clock' },
  BUILDING: { label: 'Building', color: '#7C3AED', bg: '#F5F3FF', icon: 'Sparkles' },
  DEPLOYING: { label: 'Deploying', color: '#C8963E', bg: '#FFFBEB', icon: 'Rocket' },
  DONE: { label: 'Live', color: '#4A7C59', bg: '#F0FDF4', icon: 'Check' },
  FAILED: { label: 'Failed', color: '#C25450', bg: '#FEF2F2', icon: 'X' },
};